---
- name: ec2 launcher
  hosts: localhost
  connection: local
  become: true
  vars:
      instance_type: t2.micro
      key_pair: tomcat
      image_id: ami-0fa49cc9dc8d62c84
      vpc_subnet_id: subnet-090a90ba75ea92052
      region: us-east-2
  roles:
      - tasks.yml
      
...
